# Generated by Django 2.2.1 on 2019-06-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_guest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('event', 'phone')},
        ),
    ]
